import { lazy, Suspense, useEffect, useState } from 'react';
import { accountingApi, MANUAL_CATEGORIES, AUTO_CATEGORIES } from '../api/accounting.api';
import { useProjectContext } from '@/contexts/ProjectContext';
import useUrlFilters from '@/shared/hooks/useUrlFilters';
import { useEscapeKey } from '@/shared/hooks/useDialogA11y';
import PageHeader from '@/shared/components/ui/PageHeader';
import EmptyState from '@/shared/components/ui/EmptyState';
import SkeletonTable from '@/shared/components/ui/SkeletonTable';
import Portal from '@/shared/components/ui/portal';
import Select from '@/shared/components/ui/Select';
import { Plus, X, Receipt, Trash, PencilSimple, Paperclip, UploadSimple, Lightning, DownloadSimple } from '@phosphor-icons/react';
import { toast } from '@/shared/hooks/useToast';

const ConfirmDialog = lazy(() => import('@/shared/components/ui/ConfirmDialog'));

const ALL_CATEGORIAS = [...MANUAL_CATEGORIES, ...AUTO_CATEGORIES];
const CAT_COLORS = {
  salarios: 'bg-blue-100 text-blue-800 dark:bg-blue-950/30 dark:text-blue-400',
  alquiler: 'bg-purple-100 text-purple-800 dark:bg-purple-950/30 dark:text-purple-400',
  proveedores: 'bg-amber-100 text-amber-800 dark:bg-amber-950/30 dark:text-amber-400',
  software: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-400',
  publicidad: 'bg-pink-100 text-pink-800 dark:bg-pink-950/30 dark:text-pink-400',
  impuestos: 'bg-red-100 text-red-800 dark:bg-red-950/30 dark:text-red-400',
  servicios: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-950/30 dark:text-cyan-400',
  mantenimiento: 'bg-orange-100 text-orange-800 dark:bg-orange-950/30 dark:text-orange-400',
  otros: 'bg-muted text-muted-foreground',
  comision_pasarela_pago: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950/30 dark:text-indigo-400',
  comision_gestor: 'bg-teal-100 text-teal-800 dark:bg-teal-950/30 dark:text-teal-400',
  nomina: 'bg-slate-200 text-slate-800 dark:bg-slate-800 dark:text-slate-300',
};

function isAutoGenerated(e) {
  return !!(e.source_payable_id || e.source_stripe_payout_id);
}

// CSV (RFC4180) escapando comillas dobles y comas. Primera fila = cabecera.
function buildCSV(rows) {
  const headers = ['id', 'fecha', 'concepto', 'categoria', 'importe', 'proyecto', 'origen', 'comprobante', 'notas'];
  const esc = (v) => {
    if (v === null || v === undefined) return '';
    const s = String(v);
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  };
  const lines = [headers.join(',')];
  for (const e of rows) {
    const origen = e.source_stripe_payout_id ? `stripe:${e.source_stripe_payout_id}`
      : e.source_payable_id ? `payable:${e.source_payable_id}`
      : 'manual';
    lines.push([
      esc(e.id),
      esc(e.fecha),
      esc(e.concepto),
      esc(e.categoria),
      esc(Number(e.importe).toFixed(2)),
      esc(e.proyecto_nombre || ''),
      esc(origen),
      esc(e.comprobante_url || ''),
      esc(e.notas || ''),
    ].join(','));
  }
  return lines.join('\r\n');
}

function downloadBlob(content, filename, mime = 'text/csv;charset=utf-8') {
  const blob = new Blob(['﻿' + content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function fmt(n) {
  return new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(Number(n || 0));
}
function formatDate(d) {
  if (!d) return '--';
  return new Date(d).toLocaleDateString('es-ES', { day: '2-digit', month: 'short', year: 'numeric' });
}

export default function ExpensesPage() {
  const { activeProject } = useProjectContext();
  const [expenses, setExpenses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [{ cat: filterCat }, setUrlFilter] = useUrlFilters({ cat: '' });
  const setFilterCat = (v) => setUrlFilter({ cat: v });
  const [pendingDelete, setPendingDelete] = useState(null);

  async function load() {
    setLoading(true);
    try {
      const params: Record<string, string | number> = {};
      if (activeProject?.id) params.projectId = activeProject.id;
      if (filterCat) params.categoria = filterCat;
      const res = await accountingApi.listExpenses(params);
      if (res.success) setExpenses(res.data);
    } catch (err) {
      toast({ title: 'Error cargando egresos', description: err?.data?.error || err.message, variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); }, [activeProject?.id, filterCat]);

  async function handleExport() {
    try {
      const params: Record<string, string | number> = { limit: 100, page: 1 };
      if (activeProject?.id) params.projectId = activeProject.id;
      if (filterCat) params.categoria = filterCat;
      const all: any[] = [];
      let page = 1;
      while (page <= 200) {
        const res = await accountingApi.listExpenses({ ...params, page });
        if (!res.success || !res.data || res.data.length === 0) break;
        all.push(...res.data);
        if (res.data.length < 100) break;
        page++;
      }
      if (all.length === 0) {
        toast({ title: 'Sin datos para exportar' });
        return;
      }
      const csv = buildCSV(all);
      const date = new Date().toISOString().slice(0, 10);
      downloadBlob(csv, `egresos-${date}.csv`);
      toast({ title: 'CSV descargado', description: `${all.length} registros` });
    } catch (err) {
      toast({ title: 'Error exportando', description: err?.data?.error || err.message, variant: 'destructive' });
    }
  }

  function handleDelete(id) { setPendingDelete(id); }
  async function doDelete() {
    try {
      await accountingApi.deleteExpense(pendingDelete);
      toast({ title: 'Egreso eliminado' });
      await load();
    } catch (err) {
      toast({ title: 'Error', description: err?.data?.error, variant: 'destructive' });
    } finally { setPendingDelete(null); }
  }

  const total = expenses.reduce((s, e) => s + Number(e.importe), 0);

  return (
    <div className="space-y-5">
      <PageHeader
        title="Egresos"
        subtitle={`${expenses.length} registros • Total: ${fmt(total)}`}
        actions={
          <div className="flex items-center gap-2">
            <button
              onClick={handleExport}
              aria-label="Exportar a CSV"
              disabled={expenses.length === 0}
              className="inline-flex items-center gap-2 h-9 px-3 rounded-lg border border-border bg-card text-sm font-semibold hover:bg-muted disabled:opacity-50 focus:outline-none focus:ring-2 focus:ring-primary/40"
            >
              <DownloadSimple size={14} weight="bold" /> <span className="hidden sm:inline">CSV</span>
            </button>
            <button
              onClick={() => { setEditing(null); setDialogOpen(true); }}
              aria-label="Nuevo egreso"
              className="inline-flex items-center gap-2 h-9 px-3 sm:px-4 rounded-lg bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary/40"
            >
              <Plus size={14} weight="bold" /> <span className="hidden sm:inline">Nuevo egreso</span>
            </button>
          </div>
        }
      />

      <div className="flex items-center gap-2">
        <span className="text-xs text-muted-foreground">Filtrar:</span>
        <Select<string>
          value={filterCat}
          onChange={setFilterCat}
          options={[
            { value: '', label: 'Todas las categorías' },
            ...ALL_CATEGORIAS.map(c => ({ value: c, label: c })),
          ]}
          ariaLabel="Filtrar por categoría"
          className="w-48"
        />
      </div>

      {loading ? (
        <SkeletonTable rows={5} columns={6} />
      ) : expenses.length === 0 ? (
        <div className="bg-card border border-border rounded-lg overflow-hidden">
          <EmptyState
            icon={Receipt}
            title="Sin egresos"
            description="No hay gastos registrados"
            action={
              <button
                onClick={() => setDialogOpen(true)}
                className="inline-flex items-center gap-2 h-9 px-3 rounded-lg bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary/40"
              >
                <Plus size={14} weight="bold" /> Crear el primero
              </button>
            }
          />
        </div>
      ) : (
        <>
          {/* Desktop table */}
          <div className="hidden lg:block bg-card border border-border rounded-lg overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-muted/50 text-[11px] text-muted-foreground">
                <tr>
                  <th className="text-left px-5 py-2.5 font-bold">Fecha</th>
                  <th className="text-left px-5 py-2.5 font-bold">Concepto</th>
                  <th className="text-left px-5 py-2.5 font-bold">Categoría</th>
                  <th className="text-left px-5 py-2.5 font-bold">Proyecto</th>
                  <th className="text-center px-2 py-2.5 font-bold" title="Comprobante adjunto">📎</th>
                  <th className="text-right px-5 py-2.5 font-bold">Importe</th>
                  <th className="px-5 py-2.5"></th>
                </tr>
              </thead>
              <tbody>
                {expenses.map(e => (
                  <tr key={e.id} className="border-b last:border-0 hover:bg-muted/30">
                    <td className="px-5 py-3">{formatDate(e.fecha)}</td>
                    <td className="px-5 py-3 font-semibold">
                      {e.concepto}
                      {e.notas && <div className="text-xs text-muted-foreground font-normal mt-0.5">{e.notas}</div>}
                    </td>
                    <td className="px-5 py-3">
                      <div className="flex items-center gap-1.5 flex-wrap">
                        <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-bold ${CAT_COLORS[e.categoria] || CAT_COLORS.otros}`}>
                          {e.categoria}
                        </span>
                        {isAutoGenerated(e) && (
                          <span title="Generado automáticamente por el sistema" className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[9px] font-bold bg-violet-100 text-violet-800 dark:bg-violet-950/30 dark:text-violet-400">
                            <Lightning size={9} weight="fill" /> auto
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="px-5 py-3 text-muted-foreground">{e.proyecto_nombre || <span className="italic">General</span>}</td>
                    <td className="px-2 py-3 text-center">
                      {e.comprobante_url ? (
                        <a href={e.comprobante_url} target="_blank" rel="noopener noreferrer"
                          aria-label="Ver comprobante"
                          className="inline-flex items-center justify-center h-7 w-7 rounded hover:bg-muted text-primary">
                          <Paperclip size={14} weight="bold" />
                        </a>
                      ) : <span className="text-muted-foreground/40 text-xs">—</span>}
                    </td>
                    <td className="px-5 py-3 text-right tabular-nums font-bold">{fmt(e.importe)}</td>
                    <td className="px-5 py-3 text-right">
                      <div className="inline-flex gap-1">
                        <button
                          onClick={() => { setEditing(e); setDialogOpen(true); }}
                          aria-label="Editar egreso"
                          disabled={isAutoGenerated(e)}
                          title={isAutoGenerated(e) ? 'Egreso automático: no editable' : 'Editar'}
                          className="h-8 w-8 inline-flex items-center justify-center rounded hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary/40 disabled:opacity-30 disabled:cursor-not-allowed"
                        >
                          <PencilSimple size={14} weight="bold" />
                        </button>
                        <button
                          onClick={() => handleDelete(e.id)}
                          aria-label="Eliminar egreso"
                          disabled={isAutoGenerated(e)}
                          title={isAutoGenerated(e) ? 'Egreso automático: no eliminable' : 'Eliminar'}
                          className="h-8 w-8 inline-flex items-center justify-center rounded hover:bg-red-50 dark:hover:bg-red-950/30 text-muted-foreground hover:text-red-600 dark:hover:text-red-400 focus:outline-none focus:ring-2 focus:ring-primary/40 disabled:opacity-30 disabled:cursor-not-allowed"
                        >
                          <Trash size={14} weight="bold" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Mobile cards */}
          <div className="lg:hidden space-y-2">
            {expenses.map(e => (
              <div key={e.id} className="bg-card border border-border rounded-lg p-3 flex items-start gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1.5 mb-1 flex-wrap">
                    <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-bold ${CAT_COLORS[e.categoria] || CAT_COLORS.otros}`}>
                      {e.categoria}
                    </span>
                    {isAutoGenerated(e) && (
                      <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[9px] font-bold bg-violet-100 text-violet-800 dark:bg-violet-950/30 dark:text-violet-400">
                        <Lightning size={9} weight="fill" /> auto
                      </span>
                    )}
                    {e.comprobante_url && (
                      <a href={e.comprobante_url} target="_blank" rel="noopener noreferrer"
                        className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full text-[9px] font-bold bg-primary/10 text-primary">
                        <Paperclip size={9} weight="bold" /> ver
                      </a>
                    )}
                    <span className="text-[11px] text-muted-foreground">{formatDate(e.fecha)}</span>
                  </div>
                  <p className="text-sm font-semibold truncate">{e.concepto}</p>
                  <p className="text-[11px] text-muted-foreground truncate">
                    {e.proyecto_nombre || 'General'}{e.notas ? ` · ${e.notas}` : ''}
                  </p>
                </div>
                <div className="flex flex-col items-end gap-1.5 flex-shrink-0">
                  <span className="text-sm font-bold tabular-nums">{fmt(e.importe)}</span>
                  <div className="flex gap-1">
                    <button
                      onClick={() => { setEditing(e); setDialogOpen(true); }}
                      aria-label="Editar egreso"
                      disabled={isAutoGenerated(e)}
                      className="h-7 w-7 inline-flex items-center justify-center rounded hover:bg-muted text-muted-foreground disabled:opacity-30"
                    >
                      <PencilSimple size={13} weight="bold" />
                    </button>
                    <button
                      onClick={() => handleDelete(e.id)}
                      aria-label="Eliminar egreso"
                      disabled={isAutoGenerated(e)}
                      className="h-7 w-7 inline-flex items-center justify-center rounded hover:bg-red-50 dark:hover:bg-red-950/30 text-muted-foreground hover:text-red-600 dark:hover:text-red-400 disabled:opacity-30"
                    >
                      <Trash size={13} weight="bold" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      <ExpenseDialog
        open={dialogOpen}
        onClose={() => { setDialogOpen(false); setEditing(null); }}
        expense={editing}
        activeProjectId={activeProject?.id}
        onSaved={() => load()}
      />
      {pendingDelete !== null && (
        <Suspense fallback={null}>
          <ConfirmDialog
            open={pendingDelete !== null}
            title="¿Eliminar egreso?"
            message="Este registro será eliminado permanentemente."
            tone="destructive"
            confirmLabel="Eliminar"
            onConfirm={doDelete}
            onCancel={() => setPendingDelete(null)}
          />
        </Suspense>
      )}
    </div>
  );
}

const EMPTY_FORM = (activeProjectId) => ({
  concepto: '',
  importe: '',
  categoria: 'otros',
  fecha: new Date().toISOString().slice(0, 10),
  project_id: activeProjectId || null,
  notas: '',
  comprobante_url: null,
  comprobante_key: null,
  comprobante_mime: null,
  comprobante_size_bytes: null,
});

function ExpenseDialog({ open, onClose, expense, activeProjectId, onSaved }) {
  useEscapeKey(onClose, open);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM(activeProjectId));

  useEffect(() => {
    if (open) {
      if (expense) {
        setForm({
          concepto: expense.concepto,
          importe: String(expense.importe),
          categoria: expense.categoria,
          fecha: String(expense.fecha).slice(0, 10),
          project_id: expense.project_id,
          notas: expense.notas || '',
          comprobante_url: expense.comprobante_url || null,
          comprobante_key: expense.comprobante_key || null,
          comprobante_mime: expense.comprobante_mime || null,
          comprobante_size_bytes: expense.comprobante_size_bytes || null,
        });
      } else {
        setForm(EMPTY_FORM(activeProjectId));
      }
    }
  }, [open, expense, activeProjectId]);

  if (!open) return null;

  async function handleFileChange(ev) {
    const file = ev.target.files?.[0];
    if (!file) return;
    const allowed = ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'];
    if (!allowed.includes(file.type)) {
      toast({ title: 'Formato no permitido', description: 'Solo PDF, JPG, PNG, WEBP.', variant: 'destructive' });
      return;
    }
    if (file.size > 15 * 1024 * 1024) {
      toast({ title: 'Archivo muy grande', description: 'Máximo 15MB.', variant: 'destructive' });
      return;
    }
    setUploading(true);
    try {
      const res = await accountingApi.uploadComprobante(file);
      if (res.success && res.data) {
        setForm(f => ({
          ...f,
          comprobante_url: res.data.comprobante_url,
          comprobante_key: res.data.comprobante_key,
          comprobante_mime: res.data.comprobante_mime,
          comprobante_size_bytes: res.data.comprobante_size_bytes,
        }));
        toast({ title: 'Comprobante subido' });
      }
    } catch (err) {
      toast({ title: 'Error subiendo comprobante', description: err?.data?.error || err.message, variant: 'destructive' });
    } finally {
      setUploading(false);
      ev.target.value = '';
    }
  }

  function removeComprobante() {
    setForm(f => ({ ...f, comprobante_url: null, comprobante_key: null, comprobante_mime: null, comprobante_size_bytes: null }));
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (!form.concepto || !form.importe) return;
    setSaving(true);
    try {
      const payload = {
        concepto: form.concepto,
        importe: Number(form.importe),
        categoria: form.categoria,
        fecha: form.fecha,
        project_id: form.project_id || null,
        notas: form.notas || null,
        comprobante_url: form.comprobante_url,
        comprobante_key: form.comprobante_key,
        comprobante_mime: form.comprobante_mime,
        comprobante_size_bytes: form.comprobante_size_bytes,
      };
      if (expense) {
        await accountingApi.updateExpense(expense.id, payload);
        toast({ title: 'Egreso actualizado' });
      } else {
        await accountingApi.createExpense(payload);
        toast({ title: 'Egreso registrado', description: fmt(payload.importe) });
      }
      onSaved?.();
      onClose();
    } catch (err) {
      toast({ title: 'Error', description: err?.data?.error, variant: 'destructive' });
    } finally {
      setSaving(false);
    }
  }

  const inputClass = 'w-full h-9 px-3 rounded-lg border border-border bg-muted/50 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20';

  return (
    <Portal>
      <div role="dialog" className="fixed inset-0 !m-0 z-[70] flex items-center justify-center sm:p-4">
        <div className="fixed inset-0 !m-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
        <div className="relative bg-card rounded-lg border border-border w-full max-w-md mx-4 p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">{expense ? 'Editar egreso' : 'Nuevo egreso'}</h2>
            <button
              onClick={onClose}
              aria-label="Cerrar"
              className="p-1.5 rounded-lg hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary/40"
            >
              <X size={18} weight="bold" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-3">
            <div>
              <label className="text-[11px] font-medium text-muted-foreground mb-1 block">Concepto *</label>
              <input value={form.concepto} onChange={e => setForm({ ...form, concepto: e.target.value })} placeholder="Alquiler oficina, salarios enero..." className={inputClass} required autoFocus />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-[11px] font-medium text-muted-foreground mb-1 block">Importe (EUR) *</label>
                <input type="number" step="0.01" min="0.01" value={form.importe} onChange={e => setForm({ ...form, importe: e.target.value })} className={inputClass + ' tabular-nums'} required />
              </div>
              <div>
                <label className="text-[11px] font-medium text-muted-foreground mb-1 block">Fecha *</label>
                <input type="date" value={form.fecha} onChange={e => setForm({ ...form, fecha: e.target.value })} className={inputClass} required />
              </div>
            </div>

            <div>
              <label className="text-[11px] font-medium text-muted-foreground mb-1 block">Categoría</label>
              <Select<string>
                value={form.categoria}
                onChange={(v) => setForm({ ...form, categoria: v })}
                options={MANUAL_CATEGORIES.map(c => ({ value: c, label: c }))}
                ariaLabel="Categoría"
              />
            </div>

            {/* Comprobante (PDF/JPG/PNG/WEBP, máx 15MB) */}
            <div>
              <label className="text-[11px] font-medium text-muted-foreground mb-1 block">
                Comprobante <span className="text-muted-foreground/70">(opcional, PDF/JPG/PNG/WEBP)</span>
              </label>
              {form.comprobante_url ? (
                <div className="flex items-center gap-2 px-3 py-2 rounded-lg border border-border bg-muted/30 text-xs">
                  <Paperclip size={14} weight="bold" className="text-primary flex-shrink-0" />
                  <a href={form.comprobante_url} target="_blank" rel="noopener noreferrer"
                    className="flex-1 truncate text-primary hover:underline">
                    {form.comprobante_key} {form.comprobante_size_bytes ? `· ${(form.comprobante_size_bytes / 1024).toFixed(0)} KB` : ''}
                  </a>
                  <button type="button" onClick={removeComprobante}
                    className="h-7 w-7 inline-flex items-center justify-center rounded hover:bg-muted text-muted-foreground hover:text-red-600">
                    <X size={13} weight="bold" />
                  </button>
                </div>
              ) : (
                <label className={`flex items-center gap-2 px-3 py-2 rounded-lg border border-dashed border-border bg-muted/20 text-xs cursor-pointer hover:bg-muted/40 ${uploading ? 'opacity-50 pointer-events-none' : ''}`}>
                  <UploadSimple size={14} weight="bold" className="text-muted-foreground" />
                  <span className="flex-1 text-muted-foreground">
                    {uploading ? 'Subiendo…' : 'Adjuntar comprobante (clic para seleccionar archivo)'}
                  </span>
                  <input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={handleFileChange} className="hidden" disabled={uploading} />
                </label>
              )}
            </div>

            <div>
              <label className="text-[11px] font-medium text-muted-foreground mb-1 block">Notas</label>
              <textarea value={form.notas} onChange={e => setForm({ ...form, notas: e.target.value })} rows={2} className="w-full px-3 py-2 rounded-lg border border-border bg-muted/50 text-sm outline-none resize-none focus:border-primary focus:ring-2 focus:ring-primary/20" />
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={onClose}
                className="h-9 px-4 rounded-lg border border-border bg-card text-sm font-semibold hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary/40"
              >
                Cancelar
              </button>
              <button
                type="submit"
                disabled={saving || uploading}
                className="h-9 px-4 rounded-lg bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 disabled:opacity-50 focus:outline-none focus:ring-2 focus:ring-primary/40"
              >
                {saving ? 'Guardando...' : (expense ? 'Guardar' : 'Crear egreso')}
              </button>
            </div>
          </form>
        </div>
      </div>
    </Portal>
  );
}
